---
# ROLE: sshd_config
# roles/sshd_config/tasks/main.yml

# Copy our ssh config in place

- name: install sshd config file
  become: yes
  copy: src=sshd_config dest=/etc/ssh/sshd_config
      owner=root
      group=root
      mode=0644

- name: restart ssh service
  become: yes
  service: name=sshd state=restarted
